#! /bin/bash


if [ ! -f ~/.config/hilink.conf ]; then
	curl -fSsL -o ~/.config/hilink.conf \
	https://raw.githubusercontent.com/rohan-molloy/sms-gateway/master/scripts/hilink.conf
fi
source ~/.config/hilink.conf

SesTokInfo=$(curl \
--url     "$HILINK_PROTO://$HILINK_HOST:$HILINK_PORT/api/webserver/SesTokInfo" \
--header  "Host:$HILINK_HOST" \
--user    "$HILINK_USER:$HILINK_PASSWORD" 
)
HILINK_COOKIE=$(echo "$SesTokInfo"|grep SessionID=|cut -b 10-147)
HILINK_TOKEN=$(echo "$SesTokInfo"|grep TokInfo|cut -b 10-41)

curl -fSs "$HILINK_PROTO://$HILINK_HOST:$HILINK_PORT/api/dialup/dial" \
--header "Host:$HILINK_HOST" \
--header "Cookie:$HILINK_COOKIE" \
--header "__RequestVerificationToken:$HILINK_TOKEN" \
--user   "$HILINK_USER:$HILINK_PASSWORD" \
--data   "<request><Action>1</Action></request>"



